spring:
  profiles:
    active:
    - dev
---
server:
  port: 34621
  
spring:
  application:
    name: producer
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
logging:
  level:
    org.hibernate.type: trace
